name: zipzipkus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flame: ^1.9.1
  flutter:
    sdk: flutter
  go_router: ^12.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/cartoon_landscape.jpg
    - assets/img/menu_oyna2.png
    - assets/img/menu_ayarlar.png
    - assets/img/menu_profil.png
    - assets/img/menu_cikis.png
